version: 2

project_name: hover

builds:
  - id: hover
    main: ./cmd/hover/
    binary: hover
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: hover
    builds: [hover]
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "hover_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  mode: replace
  replace_existing_artifacts: true
  name_template: "CLI {{ .Version }}"
  tag_name: "cli-v{{ .Version }}"

changelog:
  disable: true
