version: 2

project_name: hover

monorepo:
  tag_prefix: cli-

builds:
  - id: hover
    main: ./cmd/hover/
    binary: hover
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: hover
    builds: [hover]
    format: tar.gz
    name_template: "hover_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true
