package crawler

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/xml"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSitemapDiscoveryResult(t *testing.T) {
	result := &SitemapDiscoveryResult{
		Sitemaps: []string{
			"https://example.com/sitemap.xml",
			"https://example.com/sitemap2.xml",
		},
		RobotsRules: &RobotsRules{
			CrawlDelay: 1,
			Sitemaps:   []string{"https://example.com/sitemap.xml"},
		},
	}

	assert.Len(t, result.Sitemaps, 2)
	assert.NotNil(t, result.RobotsRules)
	assert.Contains(t, result.Sitemaps, "https://example.com/sitemap.xml")
}

func TestFilterURLs(t *testing.T) {
	c := &Crawler{
		config: &Config{},
	}

	tests := []struct {
		name         string
		urls         []string
		includePaths []string
		excludePaths []string
		expectedLen  int
	}{
		{
			name: "filter_with_includes",
			urls: []string{
				"https://example.com/blog/page1",
				"https://example.com/blog/page2",
				"https://example.com/admin/page1",
				"https://example.com/about",
			},
			includePaths: []string{"/blog"},
			excludePaths: []string{},
			expectedLen:  2,
		},
		{
			name: "filter_with_excludes",
			urls: []string{
				"https://example.com/page1",
				"https://example.com/page2",
				"https://example.com/admin/page1",
				"https://example.com/admin/page2",
			},
			includePaths: []string{},
			excludePaths: []string{"/admin"},
			expectedLen:  2,
		},
		{
			name:         "empty_urls",
			urls:         []string{},
			includePaths: []string{},
			excludePaths: []string{},
			expectedLen:  0,
		},
		{
			name: "no_filters",
			urls: []string{
				"https://example.com/page1",
				"https://example.com/page2",
			},
			includePaths: []string{},
			excludePaths: []string{},
			expectedLen:  2,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			filtered := c.FilterURLs(tt.urls, tt.includePaths, tt.excludePaths)
			assert.Len(t, filtered, tt.expectedLen)
		})
	}
}

func TestDiscoverSitemapsAndRobots(t *testing.T) {
	// Create test server
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/robots.txt":
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte(`User-agent: *
Disallow: /admin
Allow: /
Sitemap: https://example.com/sitemap.xml
`))
		case "/sitemap.xml":
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte(`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url><loc>https://example.com/page1</loc></url>
</urlset>`))
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer server.Close()

	c := &Crawler{
		config: &Config{
			UserAgent: "TestBot/1.0",
		},
	}

	tests := []struct {
		name              string
		domain            string
		expectSitemaps    bool
		expectRobotsRules bool
	}{
		{
			name:              "valid_domain",
			domain:            "example.com",
			expectSitemaps:    false, // Can't actually fetch from example.com
			expectRobotsRules: true,  // Should have default empty rules
		},
		{
			name:              "domain_with_protocol",
			domain:            "https://example.com",
			expectSitemaps:    false,
			expectRobotsRules: true,
		},
		{
			name:              "domain_with_www",
			domain:            "www.example.com",
			expectSitemaps:    false,
			expectRobotsRules: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx := context.Background()
			result, err := c.DiscoverSitemapsAndRobots(ctx, tt.domain)

			require.NoError(t, err)
			assert.NotNil(t, result)

			// All results should have RobotsRules (even if empty)
			assert.NotNil(t, result.RobotsRules)

			// Sitemaps list might be empty but that's OK
			// Just check it exists in result
			_ = result.Sitemaps
		})
	}
}

func TestParseSitemap(t *testing.T) {
	// Create test server for sitemap
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/sitemap.xml":
			w.Header().Set("Content-Type", "application/xml")
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte(`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url><loc>http://` + r.Host + `/page1</loc></url>
	<url><loc>http://` + r.Host + `/page2</loc></url>
</urlset>`))
		case "/sitemap_index.xml":
			w.Header().Set("Content-Type", "application/xml")
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte(`<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<sitemap><loc>http://` + r.Host + `/sitemap1.xml</loc></sitemap>
	<sitemap><loc>http://` + r.Host + `/sitemap2.xml</loc></sitemap>
</sitemapindex>`))
		case "/cdata_index.xml":
			w.Header().Set("Content-Type", "application/xml")
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte(`<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by All in One SEO -->
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<sitemap>
		<loc><![CDATA[http://` + r.Host + `/sitemap.xml]]></loc>
		<lastmod><![CDATA[2026-04-02T05:50:33+00:00]]></lastmod>
	</sitemap>
</sitemapindex>`))
		case "/empty.xml":
			w.Header().Set("Content-Type", "application/xml")
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte(`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>`))
		case "/invalid.xml":
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte(`not xml`))
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer server.Close()

	c := &Crawler{
		config: &Config{
			UserAgent: "TestBot/1.0",
		},
	}

	tests := []struct {
		name        string
		sitemapURL  string
		expectedLen int
		expectError bool
	}{
		{
			name:        "valid_sitemap",
			sitemapURL:  server.URL + "/sitemap.xml",
			expectedLen: 2,
			expectError: false,
		},
		{
			name:        "sitemap_index",
			sitemapURL:  server.URL + "/sitemap_index.xml",
			expectedLen: 0, // Will fail to fetch child sitemaps due to http/https mismatch
			expectError: false,
		},
		{
			name:        "cdata_sitemap_index",
			sitemapURL:  server.URL + "/cdata_index.xml",
			expectedLen: 0, // Will fail to fetch child sitemaps due to http/https mismatch (same as sitemap_index)
			expectError: false,
		},
		{
			name:        "empty_sitemap",
			sitemapURL:  server.URL + "/empty.xml",
			expectedLen: 0,
			expectError: false,
		},
		{
			name:        "invalid_xml",
			sitemapURL:  server.URL + "/invalid.xml",
			expectedLen: 0,
			expectError: false, // ParseSitemap doesn't return error for invalid XML
		},
		{
			name:        "not_found",
			sitemapURL:  server.URL + "/notfound.xml",
			expectedLen: 0,
			expectError: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx := context.Background()
			urls, err := c.ParseSitemap(ctx, tt.sitemapURL)

			if tt.expectError {
				assert.Error(t, err)
			} else {
				require.NoError(t, err)
				assert.Len(t, urls, tt.expectedLen)
			}
		})
	}
}

func TestXMLUnmarshalEdgeCases(t *testing.T) {
	tests := []struct {
		name     string
		xml      string
		isIndex  bool
		expected []string
	}{
		{
			name: "cdata_wrapped_urls",
			xml: `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url><loc><![CDATA[https://example.com/page1]]></loc></url>
	<url><loc><![CDATA[https://example.com/page2]]></loc></url>
</urlset>`,
			isIndex:  false,
			expected: []string{"https://example.com/page1", "https://example.com/page2"},
		},
		{
			name: "cdata_wrapped_sitemap_index",
			xml: `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<sitemap><loc><![CDATA[https://example.com/post-sitemap.xml]]></loc></sitemap>
	<sitemap><loc><![CDATA[https://example.com/page-sitemap.xml]]></loc></sitemap>
</sitemapindex>`,
			isIndex:  true,
			expected: []string{"https://example.com/post-sitemap.xml", "https://example.com/page-sitemap.xml"},
		},
		{
			name: "xml_entity_encoded_urls",
			xml: `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url><loc>https://example.com/search?q=hello&amp;page=2</loc></url>
</urlset>`,
			isIndex:  false,
			expected: []string{"https://example.com/search?q=hello&page=2"},
		},
		{
			name: "whitespace_in_loc",
			xml: `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url>
		<loc>
			https://example.com/page1
		</loc>
	</url>
</urlset>`,
			isIndex:  false,
			expected: []string{"https://example.com/page1"},
		},
		{
			name: "xml_comment_in_sitemap",
			xml: `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by a plugin -->
<?xml-stylesheet type="text/xsl" href="https://example.com/sitemap.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url><loc>https://example.com/page1</loc></url>
</urlset>`,
			isIndex:  false,
			expected: []string{"https://example.com/page1"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			data := []byte(tt.xml)
			if tt.isIndex {
				var index SitemapIndex
				err := xml.Unmarshal(data, &index)
				require.NoError(t, err)
				var urls []string
				for _, s := range index.Sitemaps {
					urls = append(urls, strings.TrimSpace(s.Loc))
				}
				assert.Equal(t, tt.expected, urls)
			} else {
				var urlSet URLSet
				err := xml.Unmarshal(data, &urlSet)
				require.NoError(t, err)
				var urls []string
				for _, u := range urlSet.URLs {
					urls = append(urls, strings.TrimSpace(u.Loc))
				}
				assert.Equal(t, tt.expected, urls)
			}
		})
	}
}

func BenchmarkFilterURLs(b *testing.B) {
	c := &Crawler{
		config: &Config{},
	}

	urls := []string{
		"https://example.com/page1",
		"https://example.com/page2",
		"https://example.com/page3",
		"https://example.com/page4",
		"https://example.com/page5",
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_ = c.FilterURLs(urls, []string{}, []string{})
	}
}

func TestIsGzipContent(t *testing.T) {
	tests := []struct {
		name            string
		contentEncoding string
		url             string
		expected        bool
	}{
		{
			name:            "gzip_header",
			contentEncoding: "gzip",
			url:             "https://example.com/sitemap.xml",
			expected:        true,
		},
		{
			name:            "gzip_header_uppercase",
			contentEncoding: "GZIP",
			url:             "https://example.com/sitemap.xml",
			expected:        true,
		},
		{
			name:            "xml_gz_suffix",
			contentEncoding: "",
			url:             "https://example.com/sitemap.xml.gz",
			expected:        true,
		},
		{
			name:            "gz_suffix_only",
			contentEncoding: "",
			url:             "https://example.com/sitemap.gz",
			expected:        true,
		},
		{
			name:            "xml_gz_suffix_uppercase",
			contentEncoding: "",
			url:             "https://example.com/SITEMAP.XML.GZ",
			expected:        true,
		},
		{
			name:            "no_compression",
			contentEncoding: "",
			url:             "https://example.com/sitemap.xml",
			expected:        false,
		},
		{
			name:            "deflate_encoding",
			contentEncoding: "deflate",
			url:             "https://example.com/sitemap.xml",
			expected:        false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := isGzipContent(tt.contentEncoding, tt.url)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestDecompressGzip(t *testing.T) {
	t.Run("valid_gzip_data", func(t *testing.T) {
		original := []byte("<?xml version=\"1.0\"?><urlset><url><loc>https://example.com/</loc></url></urlset>")

		// Compress the data
		var buf bytes.Buffer
		gzWriter := gzip.NewWriter(&buf)
		_, err := gzWriter.Write(original)
		require.NoError(t, err)
		err = gzWriter.Close()
		require.NoError(t, err)

		// Decompress and verify
		decompressed, err := decompressGzip(buf.Bytes())
		require.NoError(t, err)
		assert.Equal(t, original, decompressed)
	})

	t.Run("invalid_gzip_data", func(t *testing.T) {
		invalidData := []byte("not gzip data")
		_, err := decompressGzip(invalidData)
		assert.Error(t, err)
	})

	t.Run("empty_gzip_data", func(t *testing.T) {
		// Create empty gzip
		var buf bytes.Buffer
		gzWriter := gzip.NewWriter(&buf)
		err := gzWriter.Close()
		require.NoError(t, err)

		decompressed, err := decompressGzip(buf.Bytes())
		require.NoError(t, err)
		assert.Empty(t, decompressed)
	})
}

func TestParseSitemapGzip(t *testing.T) {
	// Helper to gzip content
	gzipContent := func(content []byte) []byte {
		var buf bytes.Buffer
		gzWriter := gzip.NewWriter(&buf)
		_, _ = gzWriter.Write(content)
		_ = gzWriter.Close()
		return buf.Bytes()
	}

	sitemapXML := []byte(`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url><loc>https://example.com/page1</loc></url>
	<url><loc>https://example.com/page2</loc></url>
</urlset>`)

	// Test server that serves gzipped sitemap
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/sitemap.xml.gz":
			// Serve gzipped content without Content-Encoding header (file-based compression)
			w.Header().Set("Content-Type", "application/gzip")
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write(gzipContent(sitemapXML))
		case "/sitemap-encoded.xml":
			// Serve with Content-Encoding: gzip header (transfer encoding)
			w.Header().Set("Content-Type", "application/xml")
			w.Header().Set("Content-Encoding", "gzip")
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write(gzipContent(sitemapXML))
		case "/sitemap.xml":
			// Normal uncompressed sitemap
			w.Header().Set("Content-Type", "application/xml")
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write(sitemapXML)
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer server.Close()

	c := &Crawler{
		config: &Config{
			UserAgent: "TestBot/1.0",
		},
	}

	tests := []struct {
		name        string
		path        string
		expectedLen int
		expectError bool
	}{
		{
			name:        "gzip_file_extension",
			path:        "/sitemap.xml.gz",
			expectedLen: 2,
			expectError: false,
		},
		{
			name:        "gzip_content_encoding",
			path:        "/sitemap-encoded.xml",
			expectedLen: 2,
			expectError: false,
		},
		{
			name:        "uncompressed_sitemap",
			path:        "/sitemap.xml",
			expectedLen: 2,
			expectError: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx := context.Background()
			urls, err := c.ParseSitemap(ctx, server.URL+tt.path)

			if tt.expectError {
				assert.Error(t, err)
			} else {
				require.NoError(t, err)
				assert.Len(t, urls, tt.expectedLen)
			}
		})
	}
}
